/**
 * AI Website Generator — shared foundation, Business Intelligence (C2),
 * Business DNA (C3), and Brand Strategy (C4).
 * Pipeline, LLM, API, and UI land in later commits.
 */

export {
  AI_BRAND_PERSONALITIES,
  AI_BRAND_POSITIONS,
  AI_BRAND_PROMISES,
  AI_BRAND_STRATEGY_FIELDS,
  AI_BUSINESS_DNA_FIELDS,
  AI_BUSINESS_PROFILE_CONFIDENCE_FIELDS,
  AI_BUSINESS_TYPES,
  AI_COLOUR_DIRECTIONS,
  AI_COLOUR_PSYCHOLOGIES,
  AI_COMMUNICATION_STYLES,
  AI_CONTACT_PREFERENCES,
  AI_CONTENT_DENSITIES,
  AI_CONVERSION_JOURNEYS,
  AI_CONVERSION_STRATEGIES,
  AI_CORE_MESSAGES,
  AI_CTA_STRATEGIES,
  AI_EMOTIONAL_JOURNEYS,
  AI_EMOTIONAL_STYLES,
  AI_FORMAL_CASUAL_AXIS,
  AI_GENERATION_STATUSES,
  AI_GENERATION_TONES,
  AI_HERO_MESSAGE_STRATEGIES,
  AI_HERO_STRATEGIES,
  AI_ICON_STYLES,
  AI_ILLUSTRATION_STYLES,
  AI_IMAGE_DIRECTIONS,
  AI_IMAGE_STYLES,
  AI_LOCAL_GLOBAL_AXIS,
  AI_LUXURY_FRIENDLY_AXIS,
  AI_MARKET_POSITIONS,
  AI_MODERN_CLASSIC_AXIS,
  AI_PHOTOGRAPHY_DIRECTIONS,
  AI_PRICE_SEGMENTS,
  AI_SECTION_EMPHASES,
  AI_STORYTELLING_STRATEGIES,
  AI_TRUST_STRATEGIES,
  AI_TYPOGRAPHY_DIRECTIONS,
  AI_UNIQUE_VALUE_PROPOSITIONS,
  AI_VISUAL_IDENTITIES,
  AI_VISUAL_STYLES,
  AI_VOICE_TONES,
  AI_WEBSITE_BLUEPRINT_VERSION,
  type AiBrandPersonality,
  type AiBrandPosition,
  type AiBrandPromise,
  type AiBrandStrategy,
  type AiBrandStrategyFieldName,
  type AiBusinessDNA,
  type AiBusinessDnaFieldName,
  type AiBusinessProfile,
  type AiBusinessProfileConfidence,
  type AiBusinessProfileConfidenceField,
  type AiBusinessType,
  type AiColourDirection,
  type AiColourPsychology,
  type AiCommunicationStyle,
  type AiContactPreference,
  type AiContentDensity,
  type AiConversionJourney,
  type AiConversionStrategy,
  type AiCoreMessage,
  type AiCtaStrategy,
  type AiDnaField,
  type AiEmotionalJourney,
  type AiEmotionalStyle,
  type AiFormalCasualAxis,
  type AiGeneratedFooter,
  type AiGeneratedHeader,
  type AiGeneratedNavItem,
  type AiGeneratedPage,
  type AiGeneratedSection,
  type AiGeneratedSeo,
  type AiGeneratedSiteMeta,
  type AiGeneratedTheme,
  type AiGenerationIntent,
  type AiGenerationOptions,
  type AiGenerationStatus,
  type AiGenerationTone,
  type AiHeroMessageStrategy,
  type AiHeroStrategy,
  type AiIconStyle,
  type AiIllustrationStyle,
  type AiImageDirection,
  type AiImageStyle,
  type AiLocalGlobalAxis,
  type AiLuxuryFriendlyAxis,
  type AiMarketPosition,
  type AiModernClassicAxis,
  type AiPhotographyDirection,
  type AiPriceSegment,
  type AiPrimaryCta,
  type AiResolvedThemeTokens,
  type AiSectionEmphasis,
  type AiStorytellingStrategy,
  type AiStrategyField,
  type AiThemeTokenPatch,
  type AiTrustStrategy,
  type AiTypographyDirection,
  type AiUniqueValueProposition,
  type AiVisualIdentity,
  type AiVisualStyle,
  type AiVoiceTone,
  type AiWebsiteBlueprint,
  type AiWebsiteBlueprintVersion,
  type AiWebsiteGenerateInput,
  type AiWebsiteGenerateResult,
  type AiWebsiteGenerationRecord,
} from "@/lib/website/ai/types";

export {
  assertAiWebsiteBlueprint,
  isAiGenerationStatus,
  isAiGenerationTone,
  isAiWebsiteBlueprint,
  isPlainObject,
  parseAiWebsiteBlueprint,
  type AiBlueprintParseResult,
  type AiBlueprintValidationIssue,
} from "@/lib/website/ai/validate";

export {
  AI_DEFAULT_PAGE_TYPES,
  AI_TEXT_LIMITS,
  aiSafeSlug,
  clampAiText,
  clampAiTextByKey,
  countBlueprintSections,
  createEmptyBlueprint,
  createEmptyBusinessProfile,
  createEmptyIntent,
  createGeneratedPage,
  createGeneratedSection,
  ensureHomePageFirst,
  findBlueprintPage,
  flattenNavItems,
  listBlueprintPageSlugs,
  mergeGenerationOptions,
  normalizeGenerateInput,
  resolveNavHref,
  type AiTextLimitKey,
} from "@/lib/website/ai/helpers";

export {
  AI_BUSINESS_INTELLIGENCE_PROVIDER_IDS,
  AI_CONFIDENCE_THRESHOLD,
  CATEGORY_DEFAULTS,
  DeterministicBusinessIntelligenceProvider,
  analyzeBusinessPrompt,
  analyzeBusinessPromptSync,
  getBusinessIntelligenceProvider,
  inferBusinessProfile,
  inferBusinessProfileFromPrompt,
  isAiBrandPersonality,
  isAiBusinessType,
  isAiColourDirection,
  isAiContactPreference,
  isAiVisualStyle,
  listBusinessIntelligenceProviders,
  profileToGenerationIntentFields,
  registerBusinessIntelligenceProvider,
  type AiBusinessIntelligenceInput,
  type AiBusinessIntelligenceProvider,
  type AiBusinessIntelligenceProviderId,
  type AiBusinessIntelligenceResult,
} from "@/lib/website/ai/intelligence";

export {
  AI_BUSINESS_DNA_PROVIDER_IDS,
  CATEGORY_DNA_DEFAULTS,
  DeterministicBusinessDnaProvider,
  createEmptyBusinessDna,
  deriveBusinessDna,
  deriveBusinessDnaSync,
  getBusinessDnaProvider,
  inferBusinessDna,
  inferBusinessDnaFromProfile,
  listBusinessDnaProviders,
  registerBusinessDnaProvider,
  type AiBusinessDnaInput,
  type AiBusinessDnaProvider,
  type AiBusinessDnaProviderId,
  type AiBusinessDnaResult,
} from "@/lib/website/ai/dna";

export {
  AI_BRAND_STRATEGY_PROVIDER_IDS,
  DeterministicBrandStrategyProvider,
  EMPTY_BRAND_STRATEGY_DEFAULTS,
  createEmptyBrandStrategy,
  deriveBrandStrategy,
  deriveBrandStrategySync,
  getBrandStrategyProvider,
  inferBrandStrategy,
  inferBrandStrategyFromDna,
  listBrandStrategyProviders,
  registerBrandStrategyProvider,
  type AiBrandStrategyInput,
  type AiBrandStrategyProvider,
  type AiBrandStrategyProviderId,
  type AiBrandStrategyResult,
} from "@/lib/website/ai/brand-strategy";
