/**
 * AI Website Generator — shared foundation, Business Planner (Phase 1),
 * Website Planner (Phase 2), Generation Orchestrator (Phase 2.5),
 * Hero Generator (Phase 3), Builder Adapter (Phase 3.5),
 * Live Hero Replacement (Phase 4), Business Intelligence (C2),
 * Business DNA (C3), Brand Strategy (C4), Website Planning (C5),
 * Website Composer (C6), Creative Director (C7), Blueprint Executor (B1),
 * and Generation pipeline (B3: OpenAI → engines → builder).
 */

export {
  AI_ANIMATION_PHILOSOPHIES,
  AI_ART_DIRECTIONS,
  AI_BRAND_PERSONALITIES,
  AI_BRAND_POSITIONS,
  AI_BRAND_PROMISES,
  AI_BRAND_STRATEGY_FIELDS,
  AI_BUSINESS_DNA_FIELDS,
  AI_BUSINESS_PROFILE_CONFIDENCE_FIELDS,
  AI_BUSINESS_TYPES,
  AI_COLOUR_DIRECTIONS,
  AI_COLOUR_PSYCHOLOGIES,
  AI_COMMUNICATION_STYLES,
  AI_CONTACT_PREFERENCES,
  AI_CONTENT_DENSITIES,
  AI_CONTENT_PRIORITIES,
  AI_CONVERSION_FLOWS,
  AI_CONVERSION_JOURNEYS,
  AI_CONVERSION_STRATEGIES,
  AI_CORE_MESSAGES,
  AI_CREATIVE_DIRECTION_FIELDS,
  AI_CTA_EMOTIONS,
  AI_CTA_FLOWS,
  AI_CTA_STRATEGIES,
  AI_EMOTIONAL_JOURNEYS,
  AI_EMOTIONAL_STYLES,
  AI_FIRST_IMPRESSIONS,
  AI_FOOTER_STRATEGIES,
  AI_FORMAL_CASUAL_AXIS,
  AI_GENERATION_STATUSES,
  AI_GENERATION_TONES,
  AI_HERO_COMPOSITIONS,
  AI_HERO_MESSAGE_STRATEGIES,
  AI_HERO_STRATEGIES,
  AI_ICON_STYLES,
  AI_ILLUSTRATION_STYLES,
  AI_IMAGE_DIRECTIONS,
  AI_IMAGE_STYLES,
  AI_INTERNAL_LINKING_STRATEGIES,
  AI_LOCAL_GLOBAL_AXIS,
  AI_LUXURY_FRIENDLY_AXIS,
  AI_MARKET_POSITIONS,
  AI_MODERN_CLASSIC_AXIS,
  AI_NAV_PATTERNS,
  AI_PHOTOGRAPHY_DIRECTIONS,
  AI_PLAN_SECTION_ROLES,
  AI_PREMIUM_LEVELS,
  AI_PRICE_SEGMENTS,
  AI_SECTION_EMPHASES,
  AI_SECTION_PACINGS,
  AI_SEO_PRIORITIES,
  AI_STORYTELLING_STRATEGIES,
  AI_TRUST_BUILDING_FLOWS,
  AI_TRUST_STRATEGIES,
  AI_TYPOGRAPHY_DIRECTIONS,
  AI_UI_DENSITIES,
  AI_UNIQUE_VALUE_PROPOSITIONS,
  AI_USER_JOURNEYS,
  AI_VISUAL_IDENTITIES,
  AI_VISUAL_RHYTHMS,
  AI_VISUAL_STORYTELLINGS,
  AI_VISUAL_STYLES,
  AI_VOICE_TONES,
  AI_WEBSITE_BLUEPRINT_VERSION,
  AI_WEBSITE_PLAN_FIELDS,
  AI_WEBSITE_PURPOSES,
  AI_WHITESPACE_STRATEGIES,
  type AiAnimationPhilosophy,
  type AiArtDirection,
  type AiBrandPersonality,
  type AiBrandPosition,
  type AiBrandPromise,
  type AiBrandStrategy,
  type AiBrandStrategyFieldName,
  type AiBusinessDNA,
  type AiBusinessDnaFieldName,
  type AiBusinessProfile,
  type AiBusinessProfileConfidence,
  type AiBusinessProfileConfidenceField,
  type AiBusinessType,
  type AiColourDirection,
  type AiColourPsychology,
  type AiCommunicationStyle,
  type AiContactPreference,
  type AiContentDensity,
  type AiContentPriority,
  type AiConversionFlow,
  type AiConversionJourney,
  type AiConversionStrategy,
  type AiCoreMessage,
  type AiCreativeDirection,
  type AiCreativeDirectionFieldName,
  type AiCtaEmotion,
  type AiCtaFlow,
  type AiCtaStrategy,
  type AiDnaField,
  type AiEmotionalJourney,
  type AiEmotionalStyle,
  type AiFirstImpression,
  type AiFooterStrategy,
  type AiFormalCasualAxis,
  type AiGeneratedFooter,
  type AiGeneratedHeader,
  type AiGeneratedNavItem,
  type AiGeneratedPage,
  type AiGeneratedSection,
  type AiGeneratedSeo,
  type AiGeneratedSiteMeta,
  type AiGeneratedTheme,
  type AiGenerationIntent,
  type AiGenerationOptions,
  type AiGenerationStatus,
  type AiGenerationTone,
  type AiHeroComposition,
  type AiHeroMessageStrategy,
  type AiHeroStrategy,
  type AiIconStyle,
  type AiIllustrationStyle,
  type AiImageDirection,
  type AiImageStyle,
  type AiInternalLinkingStrategy,
  type AiLocalGlobalAxis,
  type AiLuxuryFriendlyAxis,
  type AiMarketPosition,
  type AiModernClassicAxis,
  type AiNavPattern,
  type AiPhotographyDirection,
  type AiPlanNavigationStructure,
  type AiPlanSectionRole,
  type AiPremiumLevel,
  type AiPriceSegment,
  type AiPrimaryCta,
  type AiResolvedThemeTokens,
  type AiSectionEmphasis,
  type AiSectionPacing,
  type AiSeoPriority,
  type AiStorytellingStrategy,
  type AiStrategyField,
  type AiThemeTokenPatch,
  type AiTrustBuildingFlow,
  type AiTrustStrategy,
  type AiTypographyDirection,
  type AiUiDensity,
  type AiUniqueValueProposition,
  type AiUserJourney,
  type AiVisualIdentity,
  type AiVisualRhythm,
  type AiVisualStorytelling,
  type AiVisualStyle,
  type AiVoiceTone,
  type AiWebsiteBlueprint,
  type AiWebsiteBlueprintVersion,
  type AiWebsiteGenerateInput,
  type AiWebsiteGenerateResult,
  type AiWebsiteGenerationRecord,
  type AiWebsitePlan,
  type AiWebsitePlanFieldName,
  type AiWebsitePurpose,
  type AiWhitespaceStrategy,
} from "@/lib/website/ai/types";

export {
  assertAiWebsiteBlueprint,
  isAiGenerationStatus,
  isAiGenerationTone,
  isAiWebsiteBlueprint,
  isPlainObject,
  parseAiWebsiteBlueprint,
  type AiBlueprintParseResult,
  type AiBlueprintValidationIssue,
} from "@/lib/website/ai/validate";

export {
  AI_DEFAULT_PAGE_TYPES,
  AI_TEXT_LIMITS,
  aiSafeSlug,
  clampAiText,
  clampAiTextByKey,
  countBlueprintSections,
  createEmptyBlueprint,
  createEmptyBusinessProfile,
  createEmptyIntent,
  createGeneratedPage,
  createGeneratedSection,
  ensureHomePageFirst,
  findBlueprintPage,
  flattenNavItems,
  listBlueprintPageSlugs,
  mergeGenerationOptions,
  normalizeGenerateInput,
  resolveNavHref,
  type AiTextLimitKey,
} from "@/lib/website/ai/helpers";

export {
  BUSINESS_PLANNER_SYSTEM_PROMPT,
  BUSINESS_PLAN_FORBIDDEN_KEYS,
  BUSINESS_PLAN_KEYS,
  EXAMPLE_BUSINESS_PLAN,
  EXAMPLE_BUSINESS_PLANNER_PROMPT,
  buildBusinessPlanJsonSchemaPrompt,
  businessPlanFromProfile,
  completeBusinessPlanWithOpenAi,
  hasBusinessPlannerOpenAiCredentials,
  inferBusinessPlan,
  parseBusinessPlan,
  parseBusinessPlanFromContent,
  planBusinessFromPrompt,
  planBusinessFromPromptSync,
  resolveBusinessPlan,
  toWebsitePlan,
  type BusinessPlan,
  type BusinessPlanKey,
  type BusinessPlanParseResult,
  type BusinessPlannerInput,
  type BusinessPlannerLlmCompleter,
  type BusinessPlannerMeta,
  type BusinessPlannerOptions,
  type BusinessPlannerResult,
  type SectionPlan,
  type WebsitePlan as BusinessPlannerWebsitePlan,
} from "@/lib/website/ai/business-planner";

export {
  EXAMPLE_WEBSITE_PLAN,
  EXAMPLE_WEBSITE_PLANNER_BUSINESS_PLAN,
  WEBSITE_PLANNER_SYSTEM_PROMPT,
  WEBSITE_PLAN_FORBIDDEN_KEYS,
  WEBSITE_PLAN_KEYS,
  buildWebsitePlanJsonSchemaPrompt,
  completeWebsitePlanWithOpenAi,
  hasWebsitePlannerOpenAiCredentials,
  inferWebsitePlanFromBusinessPlan,
  inferWebsiteStructurePlan,
  parseWebsitePlan,
  parseWebsitePlanFromContent,
  planWebsiteFromBusinessPlan,
  planWebsiteFromBusinessPlanSync,
  resolveWebsiteStructurePlan,
  type WebsitePagePlan,
  type WebsitePlan,
  type WebsitePlanKey,
  type WebsitePlanParseResult,
  type WebsitePlannerInput,
  type WebsitePlannerLlmCompleter,
  type WebsitePlannerMeta,
  type WebsitePlannerOptions,
  type WebsitePlannerResult,
} from "@/lib/website/ai/website-planner";

export {
  EXAMPLE_GENERATION_PLAN_HOME_SLICE,
  EXAMPLE_ORCHESTRATOR_BUSINESS_PLAN,
  EXAMPLE_ORCHESTRATOR_WEBSITE_PLAN,
  SECTION_TO_GENERATOR,
  createGenerationPlan,
  resolveGeneratorId,
  runGenerationPlan,
  type CreateGenerationPlanInput,
  type GenerationPlan,
  type GenerationRunResult,
  type GenerationTask,
  type GenerationTaskResult,
  type RunGenerationPlanInput,
  type RunGenerationPlanOptions,
} from "@/lib/website/ai/orchestrator";

export {
  EXAMPLE_HERO_SECTION,
  EXAMPLE_HERO_TASK,
  HERO_GENERATOR_SYSTEM_PROMPT,
  HERO_HEADLINE_MAX_WORDS,
  HERO_LAYOUTS,
  HERO_SECTION_FORBIDDEN_KEYS,
  HERO_SECTION_KEYS,
  HERO_STYLES,
  HERO_SUBHEADLINE_MAX_WORDS,
  buildHeroJsonSchemaPrompt,
  completeHeroWithOpenAi,
  countWords,
  generateHero,
  generateHeroSync,
  hasHeroGeneratorOpenAiCredentials,
  inferHeroSection,
  parseHeroSection,
  parseHeroSectionFromContent,
  resolveHeroSection,
  type HeroGeneratorInput,
  type HeroGeneratorLlmCompleter,
  type HeroGeneratorMeta,
  type HeroGeneratorOptions,
  type HeroGeneratorResult,
  type HeroLayout,
  type HeroSectionContent,
  type HeroSectionKey,
  type HeroSectionParseResult,
  type HeroStyle,
} from "@/lib/website/ai/generators/hero";

export {
  DEFAULT_PRIMARY_HREF,
  DEFAULT_SECONDARY_HREF,
  EXAMPLE_BUILDER_HERO_SECTION,
  EXAMPLE_BUILDER_JSON,
  EXAMPLE_GENERATION_RUN_WITH_HERO,
  HERO_LAYOUT_TO_BUILDER,
  HERO_STYLE_TO_BUILDER,
  adaptGenerationRun,
  adaptGenerationRunToBuilder,
  adaptHeroContent,
  adaptHeroToBuilderSection,
  adapterOptionsFromLegacyHero,
  applyHeroToBlueprint,
  applyHeroToPage,
  replaceHeroInSections,
  resolveHeroLayoutFields,
  type AdaptGenerationRunInput,
  type AdaptHeroInput,
  type ApplyHeroToBlueprintResult,
  type BuilderAdapterOptions,
  type BuilderHeroContent,
  type BuilderJson,
  type BuilderSectionJson,
  type HeroBlueprintSource,
} from "@/lib/website/ai/builder-adapter";

export {
  AI_BUSINESS_INTELLIGENCE_PROVIDER_IDS,
  AI_CONFIDENCE_THRESHOLD,
  CATEGORY_DEFAULTS,
  DeterministicBusinessIntelligenceProvider,
  analyzeBusinessPrompt,
  analyzeBusinessPromptSync,
  getBusinessIntelligenceProvider,
  inferBusinessProfile,
  inferBusinessProfileFromPrompt,
  isAiBrandPersonality,
  isAiBusinessType,
  isAiColourDirection,
  isAiContactPreference,
  isAiVisualStyle,
  listBusinessIntelligenceProviders,
  profileToGenerationIntentFields,
  registerBusinessIntelligenceProvider,
  type AiBusinessIntelligenceInput,
  type AiBusinessIntelligenceProvider,
  type AiBusinessIntelligenceProviderId,
  type AiBusinessIntelligenceResult,
} from "@/lib/website/ai/intelligence";

export {
  AI_BUSINESS_DNA_PROVIDER_IDS,
  CATEGORY_DNA_DEFAULTS,
  DeterministicBusinessDnaProvider,
  createEmptyBusinessDna,
  deriveBusinessDna,
  deriveBusinessDnaSync,
  getBusinessDnaProvider,
  inferBusinessDna,
  inferBusinessDnaFromProfile,
  listBusinessDnaProviders,
  registerBusinessDnaProvider,
  type AiBusinessDnaInput,
  type AiBusinessDnaProvider,
  type AiBusinessDnaProviderId,
  type AiBusinessDnaResult,
} from "@/lib/website/ai/dna";

export {
  AI_BRAND_STRATEGY_PROVIDER_IDS,
  DeterministicBrandStrategyProvider,
  EMPTY_BRAND_STRATEGY_DEFAULTS,
  createEmptyBrandStrategy,
  deriveBrandStrategy,
  deriveBrandStrategySync,
  getBrandStrategyProvider,
  inferBrandStrategy,
  inferBrandStrategyFromDna,
  listBrandStrategyProviders,
  registerBrandStrategyProvider,
  type AiBrandStrategyInput,
  type AiBrandStrategyProvider,
  type AiBrandStrategyProviderId,
  type AiBrandStrategyResult,
} from "@/lib/website/ai/brand-strategy";

export {
  AI_WEBSITE_PLAN_PROVIDER_IDS,
  DeterministicWebsitePlanProvider,
  EMPTY_WEBSITE_PLAN_DEFAULTS,
  createEmptyWebsitePlan,
  deriveWebsitePlan,
  deriveWebsitePlanSync,
  getWebsitePlanProvider,
  inferWebsitePlan,
  inferWebsitePlanFromInputs,
  listWebsitePlanProviders,
  registerWebsitePlanProvider,
  type AiWebsitePlanInput,
  type AiWebsitePlanProvider,
  type AiWebsitePlanProviderId,
  type AiWebsitePlanResult,
} from "@/lib/website/ai/website-plan";

export {
  AI_WEBSITE_COMPOSER_PROVIDER_IDS,
  DeterministicWebsiteComposerProvider,
  composeWebsite,
  composeWebsiteBlueprint,
  composeWebsiteBlueprintFromInputs,
  composeWebsiteSync,
  getWebsiteComposerProvider,
  listWebsiteComposerProviders,
  registerWebsiteComposerProvider,
  ROLE_TO_SECTION_TYPE,
  type AiWebsiteComposerInput,
  type AiWebsiteComposerProvider,
  type AiWebsiteComposerProviderId,
  type AiWebsiteComposerResult,
} from "@/lib/website/ai/website-composer";

export {
  AI_CREATIVE_DIRECTOR_PROVIDER_IDS,
  DeterministicCreativeDirectorProvider,
  createEmptyCreativeDirection,
  deriveCreativeDirection,
  deriveCreativeDirectionSync,
  getCreativeDirectorProvider,
  inferCreativeDirection,
  inferCreativeDirectionFromInputs,
  listCreativeDirectorProviders,
  registerCreativeDirectorProvider,
  type AiCreativeDirectorInput,
  type AiCreativeDirectorProvider,
  type AiCreativeDirectorProviderId,
  type AiCreativeDirectorResult,
} from "@/lib/website/ai/creative-director";

export {
  executeWebsiteBlueprint,
  executeWebsiteBlueprintOnSite,
  type AiBlueprintExecuteInput,
  type AiBlueprintExecuteResult,
} from "@/lib/website/ai/blueprint-executor";

export {
  AI_WEBSITE_LLM_FORBIDDEN_KEYS,
  AI_WEBSITE_LLM_PROVIDER_IDS,
  AI_WEBSITE_LLM_SYSTEM_PROMPT,
  AI_WEBSITE_PROMPT_SIGNAL_KEYS,
  OpenAiWebsiteLlmProvider,
  buildPromptSignalsJsonSchemaPrompt,
  extractJsonObject,
  getWebsiteLlmProvider,
  hasOpenAiWebsiteCredentials,
  listWebsiteLlmProviders,
  parseAiWebsitePromptSignals,
  parseAiWebsitePromptSignalsFromContent,
  registerWebsiteLlmProvider,
  resolveOpenAiWebsiteConfig,
  type AiWebsiteLlmExtractInput,
  type AiWebsiteLlmExtractResult,
  type AiWebsiteLlmParseResult,
  type AiWebsiteLlmProvider,
  type AiWebsiteLlmProviderId,
  type AiWebsitePromptSignalKey,
  type AiWebsitePromptSignals,
} from "@/lib/website/ai/llm";

export {
  generateWebsiteFromPrompt,
  mergePromptSignalsIntoProfile,
  type AiWebsiteGeneratePipelineMeta,
  type AiWebsiteGeneratePipelineResult,
  type AiWebsiteGenerateServiceOptions,
} from "@/lib/website/ai/generation";
