import type { ThemeColorPalette, ThemeTokens } from "@/lib/website/theme/types";

export const DEFAULT_LIGHT_COLORS: ThemeColorPalette = {
  primary: "#111827",
  secondary: "#374151",
  accent: "#2563eb",
  success: "#15803d",
  warning: "#b45309",
  danger: "#b91c1c",
  background: "#ffffff",
  surface: "#f8fafc",
  border: "#e5e7eb",
  textPrimary: "#0f172a",
  textSecondary: "#334155",
  muted: "#64748b",
  hover: "#1f2937",
  active: "#020617",
};

export const DEFAULT_DARK_COLORS: ThemeColorPalette = {
  primary: "#fafafa",
  secondary: "#a1a1aa",
  accent: "#60a5fa",
  success: "#4ade80",
  warning: "#fbbf24",
  danger: "#f87171",
  background: "#09090b",
  surface: "#18181b",
  border: "#27272a",
  textPrimary: "#fafafa",
  textSecondary: "#d4d4d8",
  muted: "#a1a1aa",
  hover: "#e4e4e7",
  active: "#ffffff",
};

export const DEFAULT_THEME_TOKENS: ThemeTokens = {
  version: 1,
  presetId: "minimal-white",
  brand: {
    businessName: null,
    slogan: null,
    logoMediaId: null,
    faviconMediaId: null,
    brandImageMediaId: null,
  },
  colors: { ...DEFAULT_LIGHT_COLORS },
  darkMode: {
    enabled: true,
    preview: false,
    colors: { ...DEFAULT_DARK_COLORS },
  },
  typography: {
    headingFont: "'Space Grotesk', ui-sans-serif, system-ui, sans-serif",
    bodyFont: "'DM Sans', ui-sans-serif, system-ui, sans-serif",
    buttonFont: "'DM Sans', ui-sans-serif, system-ui, sans-serif",
    navigationFont: "'DM Sans', ui-sans-serif, system-ui, sans-serif",
    scale: "lg",
    headingWeight: 600,
    bodyWeight: 400,
    letterSpacing: "-0.02em",
    lineHeight: "1.65",
    paragraphWidth: "40rem",
  },
  buttons: {
    defaultVariant: "primary",
    shape: "rounded",
    shadow: "soft",
    hoverAnimation: "lift",
  },
  spacing: {
    sectionPadding: "xl",
    containerWidth: "72rem",
    gridGap: "1.75rem",
    cardPadding: "1.75rem",
    contentWidth: "40rem",
    maxWebsiteWidth: "90rem",
  },
  borders: {
    globalRadius: "0.75rem",
    cardRadius: "1rem",
    buttonRadius: "0.75rem",
    inputRadius: "0.75rem",
    imageRadius: "1rem",
    preset: "rounded",
  },
  shadows: {
    card: "soft",
    button: "soft",
    dropdown: "medium",
    modal: "strong",
    navigation: "soft",
    hero: "none",
    footer: "none",
  },
  icons: {
    style: "outlined",
  },
  animations: {
    entrance: "fade",
    duration: "420ms",
    speed: "normal",
    disabled: false,
    reduceMotion: true,
  },
  header: {
    style: "glass",
    shadow: true,
    announcementBar: false,
    navHeight: "md",
    logoPosition: "left",
    menuAlignment: "right",
  },
  footer: {
    columns: 4,
    showNewsletter: false,
    showSocial: true,
    showCopyright: true,
    background: null,
    spacing: "md",
  },
  forms: {
    inputStyle: "outline",
    focusRing: true,
  },
  cards: {
    style: "elevated",
    border: true,
    shadow: "soft",
    radius: null,
    hoverLift: true,
    hoverScale: false,
  },
  sections: {
    spacing: "xl",
    alternatingBackgrounds: false,
    alternateBackground: "#fafafa",
    containerPreset: "wide",
  },
};
